### ISSUE TITLE
Comparison to EMOD

### ISSUE THREAD

**Issue by kskyten** [jangevaare/Pathogen.jl#8]
Your package looks very exiting. I'm a statistician working with simulator based statistical models and infectious disease modeling is one important application.  Do you have experience with other disease simulators such as [EMOD](https://github.com/InstituteforDiseaseModeling/EMOD). How do they compare to Pathogen.jl?

**Comment by jangevaare** [comment]
I'm not familar with EMOD - reading a bit about it now. Thanks!

Even without knowing the full details of EMOD, I won't claim what's currently implemented in this package is entirely novel in functionality. While the package isn't based on any other existing package in any other language, I wouldn't be surprised if some or many of the same ideas have been implemented elsewhere. If anything were to be novel from an applied statistics perspective, it would likely be the data augmentation strategy which can be used to jointly infer event times and transmission networks.

But anyways, the main goal and contribution of the package has been to create a platform in the Julia language for working with individual level models of infectious disease - and with that model extensions, approximate inference methods, etc., which I'm working on as part of some of my PhD work. Julia was designed for scientific computation, and it really shows. The language has been ideal for this work as any user of the package can easily specify functions describing transition rates between disease states with full flexibility (high level language - easy to read/write. Syntax familiar to scientists using R, python and/or matlab) without sacrificing performance (julia code is aggressively optimized during compilation, with performance comparable to c++).
